# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Psr\Http\Message\RequestFactoryInterface: "@nyholm.psr7.psr17_factory"
    Psr\Http\Message\ResponseFactoryInterface: "@nyholm.psr7.psr17_factory"
    Psr\Http\Message\ServerRequestFactoryInterface: "@nyholm.psr7.psr17_factory"
    Psr\Http\Message\StreamFactoryInterface: "@nyholm.psr7.psr17_factory"
    Psr\Http\Message\UploadedFileFactoryInterface: "@nyholm.psr7.psr17_factory"
    Psr\Http\Message\UriFactoryInterface: "@nyholm.psr7.psr17_factory"

    # Register nyholm/psr7 services for autowiring with HTTPlug factories
    Http\Message\MessageFactory: "@nyholm.psr7.httplug_factory"
    Http\Message\RequestFactory: "@nyholm.psr7.httplug_factory"
    Http\Message\ResponseFactory: "@nyholm.psr7.httplug_factory"
    Http\Message\StreamFactory: "@nyholm.psr7.httplug_factory"
    Http\Message\UriFactory: "@nyholm.psr7.httplug_factory"

    nyholm.psr7.psr17_factory:
        class: Nyholm\Psr7\Factory\Psr17Factory

    nyholm.psr7.httplug_factory:
        class: Nyholm\Psr7\Factory\HttplugFactory

    App\Api\WpClient:
        arguments: [ '@Psr\Http\Client\ClientInterface', '@Psr\Http\Message\RequestFactoryInterface', '%happyr_wordpress.remote_url%' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
